---
- name: download multiple docker images
  hosts: all
  tasks:
    - name: download images from dockerhub
      docker_image:
        name: nginx
        source: pull   
      with_items:
        - nginx
        - ghost
        - tomcat
        - httpd
        
