---
- name: Configure apache2/httpd based on server type using error handling
  hosts: all
  tasks:
    - block:
       - name: Install apache2 on Ubuntu servers
         apt:
           name: apache2
           state: present
           update_cache: yes
      rescue:
        - name: Install httpd on RHEL servers
          yum:
            name: httpd
            state: present
            update_cache: yes
    - name: Edit the index.html file
      copy:
        content: "Weclome to IntelliqIT"
        dest: /var/www/html/index.html
    - block: 
        - name: Restart apache2
          service:
            name:  apache2
            state: restarted
      rescue:
        - name: Restart httpd
          service:
            name: httpd
            state: restarted
    - name: Check apache response on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.26.130
        - http://172.31.20.199
...
